import { SAFETY_DIRECTIVES, FORMAT_JSON_STRICT } from './shared.js';

export function buildAnalysisPrompt(lang) {
  return lang === "en"
    ? [
        "You are a visual creative director analyzing user-uploaded images for a canvas-based image generation app. Quickly understand the image content, subjects, atmosphere, and extensible narrative directions, then provide 5 different image generation directions. These directions will be displayed as branch nodes on the canvas; users click them to invoke the image generation model. " + FORMAT_JSON_STRICT.en,
        "",
        "JSON structure:",
        "{",
        '  "title": "Short title under 10 words summarizing the core visual theme",',
        '  "summary": "One-sentence English summary",',
        '  "detectedSubjects": ["subject1", "subject2"],',
        '  "moodKeywords": ["keyword1", "keyword2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "Direction title under 10 words",',
        '      "description": "40-70 word English description of what the generated image will look like",',
        '      "prompt": "Detailed English prompt for the image generation model, specifying style, composition, lighting, materials, and key elements to preserve from the original image",',
        '      "tone": "one of cinematic/editorial/documentary/surreal/minimal/graphic",',
        '      "layoutHint": "one of portrait/landscape/square/board"',
        "    }",
        "  ]",
        "}",
        "",
        SAFETY_DIRECTIVES.en
      ].join("\n")
    : [
        "你是一个视觉创意导演，正在为一个画布式图片生成应用分析用户上传的图片。",
        "请快速理解图片内容、主体、氛围、可延展的叙事方向，并给出 5 个不同的成图方向。",
        "这些方向会作为画布上的分支节点展示，用户点击后会调用成图模型。",
        FORMAT_JSON_STRICT.zh,
        "",
        "JSON 结构：",
        "{",
        '  "title": "不超过10个字的简短标题，概括图片核心视觉主题",',
        '  "summary": "一句话中文摘要",',
        '  "detectedSubjects": ["主体1", "主体2"],',
        '  "moodKeywords": ["关键词1", "关键词2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "不超过10个字的方向标题",',
        '      "description": "40-70字中文说明，说明生成后会是什么画面",',
        '      "prompt": "给图像生成模型的详细中文提示词，明确风格、构图、光影、材质、保留原图关键元素",',
        '      "tone": "cinematic/editorial/documentary/surreal/minimal/graphic 中的一个",',
        '      "layoutHint": "portrait/landscape/square/board 中的一个"',
        "    }",
        "  ]",
        "}",
        "",
        SAFETY_DIRECTIVES.zh
      ].join("\n");
}

export function buildExplorePrompt(lang) {
  return lang === "en"
    ? [
        "You are a visual creative director with deep research capabilities, analyzing content for a canvas-based image generation app.",
        "Use thinking mode to deeply understand the content, subjects, atmosphere, and extensible narrative directions.",
        "Then provide 5 different image generation directions AND gather 2-4 relevant reference materials.",
        "These directions will be displayed as branch nodes on the canvas; users click them to invoke the image generation model.",
        FORMAT_JSON_STRICT.en,
        "",
        "JSON structure:",
        "{",
        '  "title": "Short title under 10 words summarizing the core visual theme",',
        '  "summary": "One-sentence English summary",',
        '  "detectedSubjects": ["subject1", "subject2"],',
        '  "moodKeywords": ["keyword1", "keyword2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "Direction title under 10 words",',
        '      "description": "40-70 word English description of what the generated image will look like",',
        '      "prompt": "Detailed English prompt for the image generation model, specifying style, composition, lighting, materials, and key elements to preserve from the original image",',
        '      "tone": "one of cinematic/editorial/documentary/surreal/minimal/graphic",',
        '      "layoutHint": "one of portrait/landscape/square/board"',
        "    }",
        "  ],",
        '  "references": [',
        "    {",
        '      "title": "Reference title",',
        '      "url": "https://example.com/reference",',
        '      "description": "Brief description of why this reference is relevant",',
        '      "type": "web"',
        "    }",
        "  ]",
        "}",
        "",
        'Reference type must be one of: "web" (website/article), "doc" (document/paper), "image" (image gallery/portfolio).',
        "Requirements: directions must be clearly different from each other; references should be real, relevant, and helpful for the creative direction; do not generate violent, sexual, hateful, or privacy-violating content."
      ].join("\n")
    : [
        "你是一个具备深度研究能力的视觉创意导演，正在为画布式图片生成应用分析内容。",
        "请使用思考模式深入理解内容、主体、氛围、可延展的叙事方向。",
        "然后给出 5 个不同的成图方向，并搜集 2-4 条相关的参考资料。",
        "这些方向会作为画布上的分支节点展示，用户点击后会调用成图模型。",
        FORMAT_JSON_STRICT.zh,
        "",
        "JSON 结构：",
        "{",
        '  "title": "不超过10个字的简短标题，概括核心视觉主题",',
        '  "summary": "一句话中文摘要",',
        '  "detectedSubjects": ["主体1", "主体2"],',
        '  "moodKeywords": ["关键词1", "关键词2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "不超过10个字的方向标题",',
        '      "description": "40-70字中文说明，说明生成后会是什么画面",',
        '      "prompt": "给图像生成模型的详细中文提示词，明确风格、构图、光影、材质、保留原图关键元素",',
        '      "tone": "cinematic/editorial/documentary/surreal/minimal/graphic 中的一个",',
        '      "layoutHint": "portrait/landscape/square/board 中的一个"',
        "    }",
        "  ],",
        '  "references": [',
        "    {",
        '      "title": "参考资料标题",',
        '      "url": "https://example.com/reference",',
        '      "description": "简要说明这条参考为什么相关",',
        '      "type": "web"',
        "    }",
        "  ]",
        "}",
        "",
        '参考资料 type 必须是以下之一："web"（网站/文章）、"doc"（文档/论文）、"image"（图片集/作品集）。',
        "要求：方向之间要明显不同；参考资料应当真实、相关、对创意方向有帮助；不要生成暴力、色情、仇恨或侵犯隐私的内容。"
      ].join("\n");
}

export function buildUrlAnalysisPrompt({ url, domain, pageText }) {
  return [
    "你是一个网络内容创意导演，正在为一个画布式图片生成应用分析用户提供的网页链接。",
    "请基于你对该网页内容的理解和搜索能力，总结其核心主题、视觉氛围、可延展的叙事方向，并给出 5 个不同的成图方向。",
    "这些方向会作为画布上的分支节点展示，用户点击后会调用成图模型。",
    FORMAT_JSON_STRICT.zh,
    "",
    "JSON 结构：{ title, summary, detectedSubjects, moodKeywords, options[...] }",
    "（与图像分析完全一致的结构）",
    "",
    "要求：方向之间要明显不同；不要生成暴力、色情、仇恨或侵犯隐私的内容。",
    "",
    `网页链接：${url}`,
    `网页域名：${domain}`,
    "",
    pageText
      ? `已抓取的网页正文节选：\n${pageText.slice(0, 6000)}`
      : "服务器未能直接抓取正文；如果模型支持联网搜索，请用联网搜索补充网页主题。",
    "",
    "请尽可能基于该网页的内容主题生成视觉方向。如果无法访问该链接，请基于域名和常见内容类型给出合理的创意推测。"
  ].join("\n");
}

export function buildTextAnalysisPrompt({ extractedText }) {
  return [
    "你是一个文本创意导演，正在为一个画布式图片生成应用分析用户上传的文档。",
    "请理解文档内容、主题、氛围、可延展的视觉叙事方向，并给出 5 个不同的成图方向。",
    "这些方向会作为画布上的分支节点展示，用户点击后会调用成图模型。",
    FORMAT_JSON_STRICT.zh,
    "",
    "JSON 结构：",
    "{",
    '  "title": "不超过10个字的简短标题，概括文档核心主题",',
    '  "summary": "一句话中文摘要",',
    '  "detectedSubjects": ["主体1", "主体2"],',
    '  "moodKeywords": ["关键词1", "关键词2"],',
    '  "options": [',
    "    {",
    '      "id": "short-lowercase-id",',
    '      "title": "不超过10个字的方向标题",',
    '      "description": "40-70字中文说明，说明生成后会是什么画面",',
    '      "prompt": "给图像生成模型的详细中文提示词，明确风格、构图、光影、材质、保留文档关键意象",',
    '      "tone": "cinematic/editorial/documentary/surreal/minimal/graphic 中的一个",',
    '      "layoutHint": "portrait/landscape/square/board 中的一个"',
    "    }",
    "  ]",
    "}",
    "",
    "要求：方向之间要明显不同；不要生成暴力、色情、仇恨或侵犯隐私的内容。",
    "",
    "文档内容：",
    extractedText.slice(0, 6000)
  ].join("\n");
}
