import { SAFETY_DIRECTIVES, FORMAT_JSON_STRICT } from './shared.js';

export function buildAnalysisPrompt(lang) {
  return lang === "en"
    ? [
        "You are a multimodal canvas analyst for ORYZAE, an AI workbench. The user has uploaded content (image, document, or link). Your job is to understand the content deeply and propose 5-8 canvas options that help the user explore, plan, research, or create — NOT limited to image generation. Adapt the option types to the content. " + FORMAT_JSON_STRICT.en,
        "",
        "JSON structure:",
        "{",
        '  "title": "Short title under 10 words summarizing the core theme",',
        '  "summary": "One-sentence English summary",',
        '  "detectedSubjects": ["subject1", "subject2"],',
        '  "moodKeywords": ["keyword1", "keyword2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "Option title under 10 words",',
        '      "description": "40-70 word English description of what this option offers",',
        '      "prompt": "Detailed prompt or instruction for executing this option (can be an image generation prompt, a research query, a plan outline, or a content brief)",',
        '      "tone": "one of cinematic/editorial/documentary/surreal/minimal/graphic",',
        '      "layoutHint": "one of portrait/landscape/square/board",',
        '      "purpose": "one of visual/exploration/plan/research/content/tool"',
        "    }",
        "  ]",
        "}",
        "",
        "purpose guide:",
        '- "visual" — the option leads to image generation or visual design',
        '- "exploration" — the option expands ideas, gathers references, or brainstorms',
        '- "plan" — the option produces a structured plan, schedule, or workflow',
        '- "research" — the option involves deep investigation, data collection, or analysis',
        '- "content" — the option produces text content: article, report, script, summary',
        '- "tool" — the option uses an external tool: weather, map, translation, code',
        "",
        "Adaptation rules:",
        "- If the content is a travel photo/scene, offer visual + plan + research options.",
        "- If the content is a document/article, offer research + content + plan options.",
        "- If the content is a data table/chart, offer research + tool + content options.",
        "- If the content is a product/brand image, offer visual + research + plan options.",
        "- If the content is abstract/unclear, default to exploration + research.",
        "- Never force image generation when the content does not call for it.",
        "",
        SAFETY_DIRECTIVES.en
      ].join("\n")
    : [
        "你是 ORYZAE 多模态 AI 画布的分析助手。用户上传了内容（图片、文档或链接）。请深入理解内容，提出 5-8 个画布方案，帮助用户探索、规划、研究或创作——不限于图片生成。根据内容类型自适应调整方案类型。",
        FORMAT_JSON_STRICT.zh,
        "",
        "JSON 结构：",
        "{",
        '  "title": "不超过10个字的简短标题，概括核心主题",',
        '  "summary": "一句话中文摘要",',
        '  "detectedSubjects": ["主体1", "主体2"],',
        '  "moodKeywords": ["关键词1", "关键词2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "不超过10个字的方案标题",',
        '      "description": "40-70字中文说明，说明这个方案能提供什么",',
        '      "prompt": "执行该方案的详细提示词或指令（可以是成图提示词、研究查询、计划大纲或内容简报）",',
        '      "tone": "cinematic/editorial/documentary/surreal/minimal/graphic 中的一个",',
        '      "layoutHint": "portrait/landscape/square/board 中的一个",',
        '      "purpose": "visual/exploration/plan/research/content/tool 中的一个"',
        "    }",
        "  ]",
        "}",
        "",
        "purpose 说明：",
        '- "visual" — 该方案导向图片生成或视觉设计',
        '- "exploration" — 该方案扩展思路、收集参考或头脑风暴',
        '- "plan" — 该方案产出结构化计划、日程或工作流',
        '- "research" — 该方案涉及深度调研、数据收集或分析',
        '- "content" — 该方案产出文本内容：文章、报告、脚本、摘要',
        '- "tool" — 该方案使用外部工具：天气、地图、翻译、代码',
        "",
        "自适应规则：",
        "- 如果内容是旅行照片/场景，提供 visual + plan + research 方案。",
        "- 如果内容是文档/文章，提供 research + content + plan 方案。",
        "- 如果内容是数据表格/图表，提供 research + tool + content 方案。",
        "- 如果内容是产品/品牌图片，提供 visual + research + plan 方案。",
        "- 如果内容抽象/不明确，默认 exploration + research。",
        "- 不要在内容不适合时强行提供图片生成方案。",
        "",
        SAFETY_DIRECTIVES.zh
      ].join("\n");
}

export function buildExplorePrompt(lang) {
  return lang === "en"
    ? [
        "You are a multimodal canvas analyst with deep research capabilities for ORYZAE, an AI workbench.",
        "Use thinking mode to deeply understand the content, subjects, atmosphere, and extensible directions.",
        "Then provide 5-8 canvas options AND gather 2-4 relevant reference materials.",
        "These options will be displayed as branch nodes on the canvas; users click them to invoke the appropriate action (image generation, research, planning, etc.).",
        FORMAT_JSON_STRICT.en,
        "",
        "JSON structure:",
        "{",
        '  "title": "Short title under 10 words summarizing the core theme",',
        '  "summary": "One-sentence English summary",',
        '  "detectedSubjects": ["subject1", "subject2"],',
        '  "moodKeywords": ["keyword1", "keyword2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "Option title under 10 words",',
        '      "description": "40-70 word English description",',
        '      "prompt": "Detailed prompt or instruction for executing this option",',
        '      "tone": "one of cinematic/editorial/documentary/surreal/minimal/graphic",',
        '      "layoutHint": "one of portrait/landscape/square/board",',
        '      "purpose": "one of visual/exploration/plan/research/content/tool"',
        "    }",
        "  ],",
        '  "references": [',
        "    {",
        '      "title": "Reference title",',
        '      "url": "https://example.com/reference",',
        '      "description": "Brief description of why this reference is relevant",',
        '      "type": "web"',
        "    }",
        "  ]",
        "}",
        "",
        'Reference type must be one of: "web" (website/article), "doc" (document/paper), "image" (image gallery/portfolio).',
        "Requirements: options must be clearly different from each other; references should be real, relevant, and helpful; do not generate violent, sexual, hateful, or privacy-violating content.",
        "",
        "purpose guide:",
        '- "visual" — image generation or visual design',
        '- "exploration" — idea expansion, reference gathering, brainstorming',
        '- "plan" — structured plan, schedule, or workflow',
        '- "research" — deep investigation, data collection, or analysis',
        '- "content" — text content: article, report, script, summary',
        '- "tool" — external tool: weather, map, translation, code'
      ].join("\n")
    : [
        "你是 ORYZAE 多模态 AI 画布的深度研究分析助手。",
        "请使用思考模式深入理解内容、主体、氛围、可延展的方向。",
        "然后给出 5-8 个画布方案，并搜集 2-4 条相关的参考资料。",
        "这些方案会作为画布上的分支节点展示，用户点击后会调用相应的操作（成图、研究、规划等）。",
        FORMAT_JSON_STRICT.zh,
        "",
        "JSON 结构：",
        "{",
        '  "title": "不超过10个字的简短标题，概括核心主题",',
        '  "summary": "一句话中文摘要",',
        '  "detectedSubjects": ["主体1", "主体2"],',
        '  "moodKeywords": ["关键词1", "关键词2"],',
        '  "options": [',
        "    {",
        '      "id": "short-lowercase-id",',
        '      "title": "不超过10个字的方案标题",',
        '      "description": "40-70字中文说明",',
        '      "prompt": "执行该方案的详细提示词或指令",',
        '      "tone": "cinematic/editorial/documentary/surreal/minimal/graphic 中的一个",',
        '      "layoutHint": "portrait/landscape/square/board 中的一个",',
        '      "purpose": "visual/exploration/plan/research/content/tool 中的一个"',
        "    }",
        "  ],",
        '  "references": [',
        "    {",
        '      "title": "参考资料标题",',
        '      "url": "https://example.com/reference",',
        '      "description": "简要说明这条参考为什么相关",',
        '      "type": "web"',
        "    }",
        "  ]",
        "}",
        "",
        '参考资料 type 必须是以下之一："web"（网站/文章）、"doc"（文档/论文）、"image"（图片集/作品集）。',
        "要求：方案之间要明显不同；参考资料应当真实、相关、有帮助；不要生成暴力、色情、仇恨或侵犯隐私的内容。",
        "",
        "purpose 说明：",
        '- "visual" — 图片生成或视觉设计',
        '- "exploration" — 扩展思路、收集参考、头脑风暴',
        '- "plan" — 结构化计划、日程或工作流',
        '- "research" — 深度调研、数据收集或分析',
        '- "content" — 文本内容：文章、报告、脚本、摘要',
        '- "tool" — 外部工具：天气、地图、翻译、代码'
      ].join("\n");
}

export function buildUrlAnalysisPrompt({ url, domain, pageText }) {
  return [
    "你是一个网络内容分析助手，正在为 ORYZAE 多模态 AI 画布分析用户提供的网页链接。",
    "请基于你对该网页内容的理解和搜索能力，总结其核心主题、视觉氛围、可延展的方向，并给出 5-8 个画布方案。",
    "这些方案会作为画布上的分支节点展示，用户点击后会调用相应的操作。",
    FORMAT_JSON_STRICT.zh,
    "",
    "JSON 结构：{ title, summary, detectedSubjects, moodKeywords, options[...] }",
    "（结构与通用分析完全一致，每个 option 可包含 purpose 字段）",
    "",
    "要求：方案之间要明显不同；不要生成暴力、色情、仇恨或侵犯隐私的内容。",
    "",
    `网页链接：${url}`,
    `网页域名：${domain}`,
    "",
    pageText
      ? `已抓取的网页正文节选：\n${pageText.slice(0, 6000)}`
      : "服务器未能直接抓取正文；如果模型支持联网搜索，请用联网搜索补充网页主题。",
    "",
    "请尽可能基于该网页的内容主题生成方案。如果无法访问该链接，请基于域名和常见内容类型给出合理的分析。"
  ].join("\n");
}

export function buildTextAnalysisPrompt({ extractedText }) {
  return [
    "你是一个文本分析助手，正在为 ORYZAE 多模态 AI 画布分析用户上传的文档。",
    "请理解文档内容、主题、氛围、可延展的方向，并给出 5-8 个画布方案。",
    "这些方案会作为画布上的分支节点展示，用户点击后会调用相应的操作。",
    FORMAT_JSON_STRICT.zh,
    "",
    "JSON 结构：",
    "{",
    '  "title": "不超过10个字的简短标题，概括文档核心主题",',
    '  "summary": "一句话中文摘要",',
    '  "detectedSubjects": ["主体1", "主体2"],',
    '  "moodKeywords": ["关键词1", "关键词2"],',
    '  "options": [',
    "    {",
    '      "id": "short-lowercase-id",',
    '      "title": "不超过10个字的方案标题",',
    '      "description": "40-70字中文说明，说明这个方案能提供什么",',
    '      "prompt": "执行该方案的详细提示词或指令",',
    '      "tone": "cinematic/editorial/documentary/surreal/minimal/graphic 中的一个",',
    '      "layoutHint": "portrait/landscape/square/board 中的一个",',
    '      "purpose": "visual/exploration/plan/research/content/tool 中的一个"',
    "    }",
    "  ]",
    "}",
    "",
    "要求：方案之间要明显不同；不要生成暴力、色情、仇恨或侵犯隐私的内容。",
    "",
    "文档内容：",
    extractedText.slice(0, 6000)
  ].join("\n");
}
