import { FORMAT_JSON_STRICT, THINKING_FRAMEWORKS, META_DIRECTIVES } from './shared.js';

export function buildQualityAssessmentPrompt(lang, { workDescription, assessmentType = "general", criteria = [] }) {
  const defaultCriteriaEn = ["Clarity", "Completeness", "Accuracy", "Originality", "Usability"];
  const defaultCriteriaZh = ["清晰度", "完整性", "准确性", "原创性", "可用性"];
  const usedCriteria = criteria.length > 0 ? criteria : (lang === "en" ? defaultCriteriaEn : defaultCriteriaZh);

  return lang === "en"
    ? [
        "# Role",
        `You are a ${assessmentType} quality assessor.`,
        "",
        "# Mission",
        "Evaluate the provided work against established quality criteria and suggest concrete improvements.",
        "",
        "# Work to Assess",
        workDescription,
        "",
        "# Assessment Criteria",
        ...usedCriteria.map((c, i) => `${i + 1}. ${c}`),
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        "# Meta Directives",
        META_DIRECTIVES.en,
        "",
        "# Output Requirements",
        FORMAT_JSON_STRICT.en,
        "",
        "```json",
        "{",
        '  "overallScore": "1-10 or letter grade",',
        '  "dimensionScores": [',
        '    { "dimension": "Criterion name", "score": "1-10", "strengths": ["what works"], "weaknesses": ["what needs work"] }',
        "  ],",
        '  "topStrengths": ["Most impactful positive aspects"],',
        '  "topImprovements": ["Highest-priority improvements with specific how-to guidance"],',
        '  "benchmarkComparison": "How this compares to typical work in the same category"',
        "}",
        "```",
        "",
        "- Be specific: cite concrete examples from the work.",
        "- Balance praise and critique; do not be purely negative or purely positive.",
        "- Prioritize improvements by impact, not ease."
      ].join("\n")
    : [
        "# 角色",
        `你是 ${assessmentType} 质量评估师。`,
        "",
        "# 使命",
        "根据既定质量标准评估提供的作品，并提出具体改进建议。",
        "",
        "# 待评估作品",
        workDescription,
        "",
        "# 评估标准",
        ...usedCriteria.map((c, i) => `${i + 1}. ${c}`),
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        "# 元指令",
        META_DIRECTIVES.zh,
        "",
        "# 输出要求",
        FORMAT_JSON_STRICT.zh,
        "",
        "```json",
        "{",
        '  "overallScore": "1-10 或等级评分",',
        '  "dimensionScores": [',
        '    { "dimension": "标准名称", "score": "1-10", "strengths": ["做得好的地方"], "weaknesses": ["需要改进的地方"] }',
        "  ],",
        '  "topStrengths": ["最具影响力的积极方面"],',
        '  "topImprovements": ["最高优先级的改进，附具体操作方法"],',
        '  "benchmarkComparison": "与同类型典型作品相比如何"',
        "}",
        "```",
        "",
        "- 要具体：引用作品中的具体例子。",
        "- 平衡赞扬和批评；不要纯负面或纯正面。",
        "- 按影响力而非容易程度优先排序改进项。"
      ].join("\n");
}

export function buildImprovementPrompt(lang, { currentWork, painPoints, targetOutcome, constraints }) {
  return lang === "en"
    ? [
        "# Role",
        "You are a senior creative consultant specializing in iterative improvement.",
        "",
        "# Mission",
        "Analyze the current work, identify the most impactful improvements, and propose a concrete revision plan.",
        "",
        "# Current Work",
        currentWork,
        "",
        "# Pain Points",
        painPoints?.join(", ") || "None specified — infer from the work itself.",
        "",
        "# Target Outcome",
        targetOutcome,
        "",
        "# Constraints",
        constraints || "None specified.",
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        "# Output Requirements",
        "- 3-5 prioritized improvement areas, ranked by impact.",
        "- For each area: what's wrong, why it matters, and exactly how to fix it.",
        "- A revised version or specific edit suggestions where applicable.",
        "- Time/effort estimate for each improvement."
      ].join("\n")
    : [
        "# 角色",
        "你是专注于迭代改进的高级创意顾问。",
        "",
        "# 使命",
        "分析当前作品，识别最具影响力的改进点，并提出具体的修订计划。",
        "",
        "# 当前作品",
        currentWork,
        "",
        "# 痛点",
        painPoints?.join("、") || "未指定——从作品本身推断。",
        "",
        "# 目标成果",
        targetOutcome,
        "",
        "# 约束",
        constraints || "未指定。",
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        "# 输出要求",
        "- 3-5 个按影响力排序的优先改进领域。",
        "- 每个领域：问题是什么、为什么重要、具体如何修复。",
        "- 在适用情况下提供修订版本或具体编辑建议。",
        "- 每个改进的时间/精力估算。"
      ].join("\n");
}

export function buildMultiPerspectiveReviewPrompt(lang, { work, perspectives }) {
  const defaultPerspectivesEn = ["Creator", "User/Audience", "Expert/Critic", "Devil's Advocate"];
  const defaultPerspectivesZh = ["创作者", "用户/受众", "专家/评论家", "反面意见"];
  const usedPerspectives = perspectives?.length > 0 ? perspectives : (lang === "en" ? defaultPerspectivesEn : defaultPerspectivesZh);

  return lang === "en"
    ? [
        "# Role",
        "You are a multi-perspective review panel. Provide distinct evaluations from different stakeholder viewpoints.",
        "",
        "# Work to Review",
        work,
        "",
        "# Perspectives",
        ...usedPerspectives.map((p, i) => `${i + 1}. ${p}`),
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        "# Output Requirements",
        FORMAT_JSON_STRICT.en,
        "",
        "```json",
        "{",
        '  "perspectives": [',
        '    { "role": "Perspective name", "verdict": "supportive|concerned|mixed", "keyPoints": ["distinct insights from this viewpoint"], "priorityRequests": ["what this stakeholder needs changed"] }',
        "  ],",
        '  "consensus": ["Points all perspectives agree on"],',
        '  "tensions": ["Conflicts between perspectives and how to resolve them"],',
        '  "synthesis": "Integrated recommendation that balances all viewpoints"',
        "}",
        "```",
        "",
        "- Each perspective must offer genuinely different concerns, not just rephrase the same points.",
        "- Surface tensions honestly; do not force false consensus.",
        "- The synthesis should acknowledge tradeoffs, not pretend all concerns are equally solvable."
      ].join("\n")
    : [
        "# 角色",
        "你是多视角评审小组。从不同利益相关者的视角提供独立的评估。",
        "",
        "# 待评审作品",
        work,
        "",
        "# 视角",
        ...usedPerspectives.map((p, i) => `${i + 1}. ${p}`),
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        "# 输出要求",
        FORMAT_JSON_STRICT.zh,
        "",
        "```json",
        "{",
        '  "perspectives": [',
        '    { "role": "视角名称", "verdict": "supportive|concerned|mixed", "keyPoints": ["该视角的独特洞察"], "priorityRequests": ["该利益相关者需要改变的地方"] }',
        "  ],",
        '  "consensus": ["所有视角达成共识的点"],',
        '  "tensions": ["视角间的冲突及解决方案"],',
        '  "synthesis": "平衡所有视角的综合建议"',
        "}",
        "```",
        "",
        "- 每个视角必须提供真正不同的关切，而非只是换句话复述相同观点。",
        "- 诚实地呈现张力；不要强迫虚假的共识。",
        "- 综合建议应承认权衡，而非假装所有关切都能同等程度地解决。"
      ].join("\n");
}

export function buildABComparisonPrompt(lang, { optionA, optionB, comparisonGoal, decisionMaker }) {
  return lang === "en"
    ? [
        "# Role",
        "You are an A/B comparison analyst.",
        "",
        "# Mission",
        `Compare Option A and Option B to determine the best choice for: ${comparisonGoal}`,
        "",
        "# Option A",
        optionA,
        "",
        "# Option B",
        optionB,
        "",
        "# Decision Maker Context",
        decisionMaker || "General user with no specific constraints.",
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        "# Output Requirements",
        FORMAT_JSON_STRICT.en,
        "",
        "```json",
        "{",
        '  "winner": "A|B|tie|depends",',
        '  "winnerRationale": "Why the winner is better for this specific context",',
        '  "dimensionComparison": [',
        '    { "dimension": "Comparison axis", "winner": "A|B|tie", "margin": "slight|significant|decisive", "explanation": "Brief rationale" }',
        "  ],",
        '  "hiddenCosts": ["Non-obvious downsides of the winner"],',
        '  "whenToChooseLoser": ["Scenarios where the non-winner is actually the better choice"],',
        '  "blindSpots": ["What this comparison might be missing"]',
        "}",
        "```",
        "",
        "- Evaluate based on the decision maker's context, not generic pros/cons.",
        "- Be honest about hidden costs of the recommended option.",
        "- Identify when the 'loser' is actually the right choice."
      ].join("\n")
    : [
        "# 角色",
        "你是 A/B 对比分析师。",
        "",
        "# 使命",
        `对比选项 A 和选项 B，为以下目标确定最佳选择：${comparisonGoal}`,
        "",
        "# 选项 A",
        optionA,
        "",
        "# 选项 B",
        optionB,
        "",
        "# 决策者背景",
        decisionMaker || "无特定约束的一般用户。",
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        "# 输出要求",
        FORMAT_JSON_STRICT.zh,
        "",
        "```json",
        "{",
        '  "winner": "A|B|tie|depends",',
        '  "winnerRationale": "为什么获胜方在此特定情境下更优",',
        '  "dimensionComparison": [',
        '    { "dimension": "对比维度", "winner": "A|B|tie", "margin": "slight|significant|decisive", "explanation": "简要理由" }',
        "  ],",
        '  "hiddenCosts": ["获胜方的不明显劣势"],',
        '  "whenToChooseLoser": ["非获胜方实际上是更好选择的情形"],',
        '  "blindSpots": ["此对比可能遗漏的内容"]',
        "}",
        "```",
        "",
        "- 基于决策者的背景评估，而非通用的优缺点。",
        "- 对推荐选项的隐藏成本保持诚实。",
        "- 识别'输家'实际上是正确选择的情况。"
      ].join("\n");
}
