import { THINKING_FRAMEWORKS, META_DIRECTIVES, jsonSchemaContract } from './shared.js';

export function buildProjectPlanPrompt(lang, { goal, constraints, stakeholders, deliverables }) {
  return lang === "en"
    ? [
        "# Role",
        "You are a strategic project planner.",
        "",
        "# Mission",
        `Design a comprehensive project plan to achieve: ${goal}`,
        "",
        "# Constraints",
        constraints || "None specified.",
        "",
        "# Stakeholders",
        stakeholders?.join(", ") || "Not specified.",
        "",
        "# Deliverables",
        deliverables?.join(", ") || "Not specified.",
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        "# Meta Directives",
        META_DIRECTIVES.en,
        "",
        jsonSchemaContract("en", [
          "{",
          '  "overview": "1-paragraph project summary",',
          '  "phases": [',
          '    { "name": "Phase name", "duration": "estimated time", "objectives": ["objective1"], "deliverables": ["deliverable1"], "risks": ["risk1"] }',
          "  ],",
          '  "milestones": [',
          '    { "name": "Milestone", "targetDate": "relative date", "successCriteria": "how to know it\'s done" }',
          "  ],",
          '  "resources": ["Required resources and skills"],',
          '  "riskMitigation": ["Risk and mitigation strategy pairs"],',
          '  "successMetrics": ["How to measure project success"]',
          "}"
        ]),
        "",
        "- Include critical path identification.",
        "- Flag dependencies between phases.",
        "- Suggest checkpoints for go/no-go decisions."
      ].join("\n")
    : [
        "# 角色",
        "你是战略项目规划师。",
        "",
        "# 使命",
        `设计一个全面的项目计划以实现：${goal}`,
        "",
        "# 约束",
        constraints || "未指定。",
        "",
        "# 利益相关者",
        stakeholders?.join("、") || "未指定。",
        "",
        "# 交付物",
        deliverables?.join("、") || "未指定。",
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        "# 元指令",
        META_DIRECTIVES.zh,
        "",
        jsonSchemaContract("zh", [
          "{",
          '  "overview": "一段项目摘要",',
          '  "phases": [',
          '    { "name": "阶段名称", "duration": "预估时间", "objectives": ["目标1"], "deliverables": ["交付物1"], "risks": ["风险1"] }',
          "  ],",
          '  "milestones": [',
          '    { "name": "里程碑", "targetDate": "相对日期", "successCriteria": "完成的判断标准" }',
          "  ],",
          '  "resources": ["所需资源和技能"],',
          '  "riskMitigation": ["风险与缓解策略配对"],',
          '  "successMetrics": ["衡量项目成功的方式"]',
          "}"
        ]),
        "",
        "- 包含关键路径识别。",
        "- 标记阶段间的依赖关系。",
        "- 建议用于 go/no-go 决策的检查点。"
      ].join("\n");
}

export function buildLearningPathPrompt(lang, { subject, currentLevel, targetLevel, timeCommitment, preferredFormats }) {
  return lang === "en"
    ? [
        "# Role",
        "You are a curriculum designer and learning strategist.",
        "",
        "# Mission",
        `Create a personalized learning path for ${subject}.`,
        "",
        "# Learner Profile",
        `Current level: ${currentLevel}`,
        `Target level: ${targetLevel}`,
        `Time commitment: ${timeCommitment}`,
        `Preferred formats: ${preferredFormats?.join(", ") || "mixed"}`,
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        jsonSchemaContract("en", [
          "{",
          '  "pathName": "Descriptive path title",',
          '  "estimatedDuration": "Total estimated time",',
          '  "stages": [',
          '    { "stage": 1, "name": "Stage name", "topics": ["topic1"], "resources": ["book/course/resource"], "practice": "Suggested practice activity", "milestone": "How to verify mastery" }',
          "  ],",
          '  "parallelTracks": ["Optional parallel learning tracks for breadth"],',
          '  "assessmentStrategy": "How to self-assess progress",',
          '  "fallbackPlan": "What to do if stuck or falling behind"',
          "}"
        ]),
        "",
        "- Sequence topics by dependency, not just difficulty.",
        "- Balance theory and practice at each stage.",
        "- Include spaced repetition or review checkpoints."
      ].join("\n")
    : [
        "# 角色",
        "你是课程设计师和学习策略师。",
        "",
        "# 使命",
        `为 ${subject} 创建个性化学习路径。`,
        "",
        "# 学习者画像",
        `当前水平：${currentLevel}`,
        `目标水平：${targetLevel}`,
        `时间投入：${timeCommitment}`,
        `偏好格式：${preferredFormats?.join("、") || "混合"}`,
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        jsonSchemaContract("zh", [
          "{",
          '  "pathName": "描述性路径标题",',
          '  "estimatedDuration": "总预估时间",',
          '  "stages": [',
          '    { "stage": 1, "name": "阶段名称", "topics": ["主题1"], "resources": ["书籍/课程/资源"], "practice": "建议的练习活动", "milestone": "如何验证掌握程度" }',
          "  ],",
          '  "parallelTracks": ["用于拓展广度的可选并行学习轨道"],',
          '  "assessmentStrategy": "如何自我评估进度",',
          '  "fallbackPlan": "卡住或落后时的应对策略"',
          "}"
        ]),
        "",
        "- 按依赖关系而非仅按难度排列主题。",
        "- 每个阶段平衡理论和实践。",
        "- 包含间隔重复或复习检查点。"
      ].join("\n");
}

export function buildSchedulePrompt(lang, { events, priorities, flexibility, constraints }) {
  return lang === "en"
    ? [
        "# Role",
        "You are a schedule optimization specialist.",
        "",
        "# Mission",
        "Create an optimized schedule that balances priorities, constraints, and human energy patterns.",
        "",
        "# Events",
        ...events.map((e, i) => `${i + 1}. ${e}`),
        "",
        "# Priorities",
        priorities?.join(", ") || "All equal.",
        "",
        "# Flexibility",
        flexibility || "Medium — some items can move.",
        "",
        "# Constraints",
        constraints?.join(", ") || "None specified.",
        "",
        "# Output Requirements",
        "- Time-blocked schedule with buffer zones.",
        "- Identify potential conflicts and suggest resolutions.",
        "- Account for context-switching cost between different types of work.",
        "- Suggest energy-peak alignment (deep work vs shallow work)."
      ].join("\n")
    : [
        "# 角色",
        "你是日程优化专家。",
        "",
        "# 使命",
        "创建一个平衡优先级、约束和人类精力模式的优化日程。",
        "",
        "# 事件",
        ...events.map((e, i) => `${i + 1}. ${e}`),
        "",
        "# 优先级",
        priorities?.join("、") || "全部同等。",
        "",
        "# 灵活度",
        flexibility || "中等——部分事项可以调整。",
        "",
        "# 约束",
        constraints?.join("、") || "未指定。",
        "",
        "# 输出要求",
        "- 分时段的日程，含缓冲区域。",
        "- 识别潜在冲突并建议解决方案。",
        "- 考虑不同类型工作之间的上下文切换成本。",
        "- 建议精力峰值对齐（深度工作 vs 浅层工作）。"
      ].join("\n");
}

export function buildDecisionMatrixPrompt(lang, { decision, options, criteria, weights }) {
  return lang === "en"
    ? [
        "# Role",
        "You are a decision analysis consultant.",
        "",
        "# Mission",
        `Help the user make an informed decision about: ${decision}`,
        "",
        "# Options",
        ...options.map((o, i) => `${i + 1}. ${o}`),
        "",
        "# Criteria",
        ...criteria.map((c, i) => `${i + 1}. ${c}`),
        "",
        "# Weights",
        JSON.stringify(weights || {}),
        "",
        "# Thinking Framework",
        THINKING_FRAMEWORKS.en,
        "",
        jsonSchemaContract("en", [
          "{",
          '  "recommendation": "Top recommendation with rationale",',
          '  "matrix": [',
          '    { "criterion": "Criterion name", "optionA": "score 1-10", "optionB": "score 1-10", "weight": "0-1" }',
          "  ],",
          '  "scores": [',
          '    { "option": "Option name", "weightedScore": "calculated", "strengths": ["strength1"], "weaknesses": ["weakness1"] }',
          "  ],",
          '  "sensitivityAnalysis": "How the recommendation changes if weights shift",',
          '  "riskScenarios": ["What could go wrong with the recommended option"]',
          "}"
        ]),
        "",
        "- Score each option against each criterion objectively.",
        "- Surface hidden assumptions behind each criterion.",
        "- Include a 'no decision' option if the analysis suggests waiting."
      ].join("\n")
    : [
        "# 角色",
        "你是决策分析顾问。",
        "",
        "# 使命",
        `帮助用户就以下事项做出知情决策：${decision}`,
        "",
        "# 选项",
        ...options.map((o, i) => `${i + 1}. ${o}`),
        "",
        "# 标准",
        ...criteria.map((c, i) => `${i + 1}. ${c}`),
        "",
        "# 权重",
        JSON.stringify(weights || {}),
        "",
        "# 思维框架",
        THINKING_FRAMEWORKS.zh,
        "",
        jsonSchemaContract("zh", [
          "{",
          '  "recommendation": "首选推荐及理由",',
          '  "matrix": [',
          '    { "criterion": "标准名称", "optionA": "评分 1-10", "optionB": "评分 1-10", "weight": "0-1" }',
          "  ],",
          '  "scores": [',
          '    { "option": "选项名称", "weightedScore": "计算得分", "strengths": ["优势1"], "weaknesses": ["劣势1"] }',
          "  ],",
          '  "sensitivityAnalysis": "如果权重变化，推荐会如何改变",',
          '  "riskScenarios": ["推荐选项可能出错的情形"]',
          "}"
        ]),
        "",
        "- 客观地为每个选项在每个标准上评分。",
        "- 揭示每个标准背后的隐藏假设。",
        "- 如果分析建议等待，包含一个'不做决定'的选项。"
      ].join("\n");
}
